### ISSUE TITLE
Prettier styling?

### ISSUE THREAD

**Issue by amsam0** [ct-js/ct-js-old#185]
This would give a consistent style throughout code. 

I believe I have the main idea of the current 'style' here:
```json
{
  "arrowParens": "avoid",
  "bracketSpacing": false,
  "htmlWhitespaceSensitivity": "css",
  "insertPragma": false,
  "jsxBracketSameLine": false,
  "jsxSingleQuote": true,
  "printWidth": 120,
  "proseWrap": "never",
  "quoteProps": "as-needed",
  "requirePragma": false,
  "semi": true,
  "singleQuote": true,
  "tabWidth": 4,
  "trailingComma": "none",
  "useTabs": false,
  "vueIndentScriptAndStyle": true
}
```
[prettier.io playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAEnADYkQDqEATiQCYAUwA5tXHLlM-gLz4A6IABalyggDT5W7eHV74A5IKq06ghZIDOOEghjzUAQxKa4k6AFkI6UwHkAbnGriAvgEp8wflG-58OVAYAQmkOHC43YDYYdGoofCh0MhcAbm9fPz8Aeiz8ABVbABFbJHxC6AV9Gzh8akMoOggAW394tganDN19RJa+C0MYIQA6VHIafAYBoeG6huaGDwAqfABGAFEAagB2N2GYCABlGGpw5kXZuAAHEkMwOAYs-n5h57pNrJxmSUFBN3T4rUOLF4gAeOg4ez4MC3TSaAByhiacB4CmIZEoNHoCnwuBguh4wAABgBNaz4QxsfD2HDaA7UBLoJoAIyc+AAJMBGS0XESXPhLNY7I5qITBdUHE4XAA+AGZfCgzQnaDMaVc0KcZjDTQkHD3Bj4AAMklW+D2BwAqlcrk4AMKGUyLfCbKRsMJcbW6-Wrc0QAAyEAA7naHQ8PC5QVkldQVbLAX4WG7NcMEHRNBQcEMGBI-vgAPwCECF-ClRVXer4JUATwJwGAkHI1FKSn40irChcMokhcjmnLUGl+BcGT8oLgTTj-Bg6qTcDkw58MEj47j8q5DG0ulg-3jmQLgleIBHmVKgiCggXx8jEPs0rSPigLhA4hAECuuGgmmQoEpMcDAAVKQQL8UEMewIBwOhnxAZk6jAABrDhDnLMAzmQIwTDMYQYCaEgKCETM4D7O44EOYDM0hTMq2QcA4Wg8JTGoGB-zqZgmkMdDjFMF8ACtNAADwAITgxCYEOJE4D9cI4E4zDeIEw4zl0ABFdAIHgZATnQLDy2oRiaOZQxWRIaCrlOWAMzoIZkFWAAmY0QDMiBTAoOorhoqA4BFaCAEc1PgFi3xAkAHQAWk8uc52gtg-JwNgWMMNiOKQDDuJAUwmhwTTqG0l9tC4FT-JkpAtKwmAjMs6ykAAFhfE5DB0M5bWadiPOgGSX2qPIjJA1KsPsbSAEkOlgQ4wFOd8AEEGmOGtitKzsgA)

Personally, I find it much easier to write a bunch of messy code, then run prettier and get it all cleaned up.

Edit: I've updated it so it should look more "normal."

Got a branch here: https://github.com/naturecodevoid/ct-js/tree/prettier_formatting
A small downside:
When you write:
```js
const fs = null,
      path = null;
```
the indenting gets messed up.

A possible solution: https://prettier.io/docs/en/ignore.html#javascript

**Comment by CosmoMyzrailGorynych** [comment]
Is there a way for Prettier to work with tag files??

**Comment by amsam0** [comment]
I was thinking it could use the pug plugin but might be different types of files

**Comment by CosmoMyzrailGorynych** [comment]
Hm, then it probably will work.

**Comment by amsam0** [comment]
I can add it to the branch; see https://prettier.io/docs/en/plugins.html.

**Comment by CosmoMyzrailGorynych** [comment]
It would be really cool :heart: Then it would cover all our codebase.

**Comment by amsam0** [comment]
Should I create a PR?

Also, I had to make a fork of the pug plugin; it wouldn't format `.tag` files

Edit: Got a few errors for whatever reason that might have caused other files not to be formatted, but mostly it's working here: https://github.com/naturecodevoid/ct-js/tree/prettier_formatting

**Comment by CosmoMyzrailGorynych** [comment]
I'll try to check the `prettier_formatting` branch today; have no possibility to dive in it atm :woozy_face:

**Comment by CosmoMyzrailGorynych** [comment]
![image](https://user-images.githubusercontent.com/3174357/81045965-6cbd9f00-8f0b-11ea-88ab-b8fb1be3f5f6.png)

UUUUUUUHHH

**Comment by CosmoMyzrailGorynych** [comment]
And so it breaks in a number of places. Anything like `|  string`  (two or more spaces after the pipe) breaks a file, and I see inconsistencies in tag interpolation:
```pug
input(
  onchange='{wire(\'global.currentProject.settings.desktopMode\')}' // works
)
span=`{voc.launchModes.${key}}` // turns into broken "span= ;`{voc.launchModes.${key}}`"
```

After that, it fails to read these files again, because they are now broken.

Besides that, prettier is quite opinionated and this results in several inconveniences, most notably with `property: [{a: "b"}]` structures, where Prettier explodes this line into 5 when a reasonable number is at max 3. Now, there is a standard already that can be seen in existing files, though it is not fully fleshed out in some formatter's manifest. (It is partially described in .eslintrc, though, and it conflicts with Prettier.) The golden rule of coding standards is that you pick it once and never change. (And it stays so for, like, 6 years?)

**Comment by CosmoMyzrailGorynych** [comment]
Now, ESLint has a nice amount of style checks (https://eslint.org/docs/rules/#stylistic-issues), so maybe improve ESLint instead of incorporating a new tool in the build pipeline. It also works well with VSCode and has tons of other goodies that disallow one shooting themselves in their foot. I can see a plugin https://www.npmjs.com/package/eslint-plugin-pug that does not mess with pug syntax but works with `script` tags only.

So yeah, let's instead try to do the same with ESLint. I'll release v1.3 and will look into the issue again.

**Comment by CosmoMyzrailGorynych** [comment]
Seems to work but there is a lot to fix in the linted code :D

![image](https://user-images.githubusercontent.com/3174357/81495920-f43e5000-9307-11ea-91fa-187d39a51732.png)

**Comment by amsam0** [comment]
are you able to push to my branch? if not, I can make a pr

**Comment by CosmoMyzrailGorynych** [comment]
I cannot do it directly. The linter works, I just need to fix its warnings in tag files, and then I'll push to develop.

Focus on other issues, if you want :D

**Comment by amsam0** [comment]
Ok, been working on some other projects, sorry!

**Comment by CosmoMyzrailGorynych** [comment]
I think we can count it as closed with https://github.com/ct-js/ct-js/commit/110bbbd2076b5c03f6bc6ef27e82e4810bc84dcd

No automatic fixes, unfortunately, but a linter that requires manual edits is better than no linter at all.
