### ISSUE TITLE
Bitmap Fonts Crash The IDE

### ISSUE THREAD

**Issue by yonderbread** [ct-js/ct-js-old#220]
**Describe the bug**
When I load a .ttf file and select to generate a bitmap font for it, then launch my game, it freezes up and does **nothing.**

**To Reproduce**
1. Load a .ttf font
2. Check generate bitmap font
3. Launch your game.
Boom! frozen

**Expected behavior**
To load my font and allow me to access it programmatically. 

**Screen Recording:**
https://streamable.com/6b39vr

**Versions:**
 - OS: Windows 10
 - ct.js version: 1.4.1

**Comment by pennro-se** [comment]
I would like to add, it seems exporting the game with generate bitmap font selected also hangs.

**Comment by yonderbread** [comment]
> 
> 
> I would like to add, it seems exporting the game with generate bitmap font selected also hangs.

Well it's good to know that it's not just me haha

**Comment by amsam0** [comment]
Might be an issue with nw.js

**Comment by CosmoMyzrailGorynych** [comment]
The thing that some fonts work, others don't, and there is currently no visible pattern.
For example, [this font](https://github.com/ct-js/ct-js/files/5115118/f4c144913-bfa8-45d0-bf64-a6430f55485e.zip) works.

There may be a bug in the current font-to-bitmap converter, as it is a fork of a 3rdparty package, heavily edited by me and I can't definitely say it is 100% bug-free.
There may be an issue with nw.js — it definitely had issues (well, native crashes) with these bitmap fonts, and because of them ct.js currently has its debugger embedded.
The fonts themselves may be buggy (like broken symbol tables, wrong metadata) that can be tolerable by text processors and such but crash ct.js. Ct.js uses [opentype.js](https://github.com/opentypejs/opentype.js/) to read and draw fonts.

If anyone has time and energy to look into this issue, do it :D

**Comment by pennro-se** [comment]
Do you know of any other fonts that work with ct.js? I'm testing a bunch of fonts but I've yet to find another that works.

**Comment by pennro-se** [comment]
If possible, could you run the attached fonts through [bmGlyph](https://www.bmglyph.com/) with the Sparrow configuration, @naturecodevoid? [I've heard](https://www.html5gamedevs.com/topic/30443-how-to-win-at-pixiextrasbitmaptext/?do=findComment&comment=174739) that produces the correct version of this bitmap font format and see what I can build off that. I'm not quite sure who designed this bitmap font format or what it's called so it's hard to find specifications for it and this seems simpler than trying to reverse engineer PixiJS's loader.

Attached:
[fonts.zip](https://github.com/ct-js/ct-js/files/5117355/fonts.zip)

**Comment by yonderbread** [comment]
I really need a pixel font that will display well on a very small resolution (160x160) without freezing my editor.
