### ISSUE TITLE
Wrapper function for onCreate appearing unexpectedly in room's On Create IDE

### ISSUE THREAD

**Issue by oaklandgit** [ct-js/ct-js-old#279]
**Describe the bug**
See this screenshot. Notice how the onCreate function is appearing in the IDE. Also notice the repeated line number 1.
The problem fixed itself after restarting ctjs.

<img width="544" alt="Screen Shot 2021-04-11 at 1 52 36 PM" src="https://user-images.githubusercontent.com/421615/114320975-79f4ed80-9acd-11eb-9d30-d70944fc99da.png">

**To Reproduce**
Unfortunately, I'm not sure how to reproduce this.

**System information report**
Ct.js v1.7.0 😽 (packaged)

NW.JS v0.51.2
Chromium v88.0.4324.182
Node.js v15.8.0
Pixi.js v5.1.2

WebGL available
WebGL vendor Intel Inc.
WebGL renderer Intel(R) Iris(TM) Plus Graphics OpenGL Engine
OS darwin x64 // Darwin 20.3.0

**Comment by oaklandgit** [comment]
Can happen with any tab. (e.g. On Draw).

**Comment by CosmoMyzrailGorynych** [comment]
This is the result of my workarounds for monaco's issue https://github.com/microsoft/monaco-editor/issues/45

> The problem fixed itself after restarting ctjs.

Can be fixed by closing and reopening type editor / room events editor.

> Unfortunately, I'm not sure how to reproduce this.

One of the ways to get a variation of this bug:

1. Open a code editor of a type or a room
2. Write anything on the first line
3. Alt+Up arrow
4. The line disappears 
5. Reopen the asset editor
6. You can now see a wrapping function. (Another one gets created and is invisible so removing the one inside your code will fix the issue)
