### ISSUE TITLE
Camera is null?

### ISSUE THREAD

**Issue by Tiger-The-Cat** [ct-js/ct-js-old#299]
Everything seems to be fine with my game, but I keep getting this console error:
![image](https://user-images.githubusercontent.com/70044734/129456815-a290307a-b825-494d-8783-854c2161de8c.png)
ct.js system code:
![image](https://user-images.githubusercontent.com/70044734/129456820-0f4c1ffc-35f4-49b3-827a-25b1c2729263.png)
it seems that the ct.camera is null.
Thanks!

**Comment by SaberTooth-Studios** [comment]
I've had that happen to me if I set the main room as a ui room, instead of having a ui room append non-ui into the stage, have the non-ui append the ui

**Comment by ghost** [comment]
NOTE BEFORE READING: I'm not very smart so this might be wrong

Where are you running you're ct.js game? If you open the index.html file locally into your web browser lots of things (including ct.camera) just don't work. If you're running a ct.js preview from the ct.js app then ct.camera shouldn't be null, if you're running the index.html file hosted on a website/webserver ct.camera shouldn't be null, and if you're running it as a desktop app packaged using electron, nw.js, ect it shouldn't be null, and if you're running it as a mobile app packaged using cordova it shouldnt be null (and I know you're not using cordova because you have the debugger open and its in a desktop chrome style) the only way for ct.camera being null to not be a bug and still be null is if you're running the index.html file in your browser locally, otherwise its a bug and idk how to fix it sorry.

**Comment by terjegran** [comment]
I've run into this issue as well. I encounter this issue when a resize occurs while the content is being loaded. That means that the ct-elements are not ready yet. I've made a temporary fix to the issue by editing the "fittoscreen" catmod to skip scaling while loading. I add the following code at the start of the resize function:

`if (PIXI.Loader.shared.loading) return;`

There might be better solutions, but that at least fixes the issue for me at the moment.

**Comment by CosmoMyzrailGorynych** [comment]
Closed in https://github.com/ct-js/ct-js/commit/b0ee8ce59c4d66345854f65eb113e6ea89db02e8
