### ISSUE TITLE
Catnip: Visual scripting language (with linear grammar)

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [ct-js/ct-js-old#331]
**Is your feature request related to a problem?**

The aim of this issue is mainly to make the upcoming addition transparent for everyone.

From what I've seen while working with children and presenting different engines to them, the biggest issue for them was not a language barrier, not the complexity of coding concepts, but the goddamn syntax. They don't format code, they skip brackets, and these seemingly minor mistakes draw frustration and distract what's actually important.

Additionally, my practice from working with Unreal Engine's Blueprints system has shown that visual scripting may be as full, as effective, as fast as coding with, well, letters. It can also be better than that.

By no means this will replace the current scripting workflow in ct.js; it will be an additional way to code.

**Describe the solution you'd like**

Riot.js-based visual scripting editor with type-in and DnD workflows.

Challenges:

- [x] Make it extendable — modules must be able to provide their own blocks
- [x] Make it localizable
- [x] Make it fast both to type and compose with D&D
- [x] Keep the linear grammar (this should be easy) — the converter should be blazingly fast and linear. Each block corresponds to a determined string of JS code.
- [x] Variable management. Remember that JS variables can be of any type.
- [ ] Ideally produce properly formatted code, add comments to the output so it can be traced back to the visual scripts.
- [x] Clearly communicate about asynchronous methods and their effects.
- [ ] Make examples of great games!

![Frame 32](https://github.com/ct-js/ct-js/assets/3174357/b6c5672f-3e51-4652-a88a-c501c8c2a088)

**Steps to implement in no particular order:**

- [x] `.d.ts` parser to form a list of blocks from catmods and ct.js API — getting good results here.
  - [x] Need to also store localization data and block description somewhere, probably in a separate file as if we put it in TSDoc, it will appear in text-based coding, too. Unless we mod the TSDoc renderer in monaco-editor.
    - With the latter, the feature is called "HoverProvider":
      - https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.HoverProvider.html
      - https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.Hover.html
      - https://microsoft.github.io/monaco-editor/typedoc/functions/languages.registerHoverProvider.html
    - With typescript, the worker's method is called QuickInfo, and can be found as TypeScript's worker's `getQuickInfoAtPosition` method. (https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.typescript.TypeScriptWorker.html#getQuickInfoAtPosition)
      - The method's result runs through an adapter to become Hover. (https://github.com/microsoft/monaco-editor/blob/main/src/language/typescript/languageFeatures.ts#L679)
    - TL;DR a modified version can be registered. 
- [x] Settle on data structure of block notation
- [x] Plug modded commands into built-in ones and update the lists on the go
- [x] Make a DnD code editor
  - [x] Block library in UI
    - [x] Fuzzy search in this library
  - [x] Bare minimum (a la Scratch)
  - [x] Fuzzy-search and insert in-between blocks and at the end of the script with automatic :focus movement
  - [x] Multiple selection of blocks with DnD
  - [x] Context menu operations
    - [x] Cut/copy/paste
    - [x] Delete 
  - [x] Hook `monaco-editor` into block editor for custom TS/CoffeeScript code 
  - [x] i18n
  - [x] Menus for picking asset names; using asset IDs for these.
- [x] Make a JS compiler for block scripts
- [x] Make a base block library for built-in language statements like `if`, `if-else`, `while` `for...of` and operators like `a+b`, `a AND b`, `-a`, `!a`, …
  - Can be a good community event
- [x] Creation of variables in events, properties in scriptable asset types, and list properties of linked behaviors.
  - [x] There should also be blocks for direct write of properties of an object
- [x] Handle cases when a block declaration is not found (e.g. catmod updated/got disabled) 

**Describe alternatives you've considered (optional)**

Node-based solution. (Too hard to implement the converter; ideally it needs a VM and not a converter as there are structures in node languages that don't translate to JS. Think of overlapping loops, for example.)

Integrating Scratch blocks / Google Blockly. (The renderer is hardcoded with SVG to death, can't optimistically extend or modify it)

**Comment by blurymind** [comment]
looks cool!
Your current approach is very similar to scratch, which I am not a fan of - since its slower to use, but almost the same as coding. It doesnt take enough advantage of the visual side of coding.

I would personally prefer if conditions were in their own left side column -similar to construct and gdevelop.

That makes logic surprisingly easier to read vs having both conditions and actions in a single column. It also reduces scrolling.It sort of takes advantage of the visual nature to make it easier.

Another thing that helps alot is having little thumbnails of objects being generated from their sprites. It makes it much easier to see and find logic associated with enemies/npc/players at a glance.

Finally ability to group logic, so one can collapse/uncollapse it makes things much easier when you have a lot of it.
Unreal lets you group nodes, gdevelop and construct both let you make event groups.


One killer feature that ct.js can totally hit out of the park compared to the others is the ability to make event nodes with javascript.

This is something that gdevelop really suffers from atm. It extension api is very clunky to use and takes in tons of boilerplate and fiddling to get the simplest things working in terms of making new events and object types


So in terms of goals for a good visual scripting design I would look for these things for example:
-  how fast is it to read logic at a glance - using less words to describe it and colors and images to communicate more than what text does. Understanding it at a glance. Here layout can help - for example the two column thing does make a huge difference, since your brain starts making distinction between horizontally switching between condition/action and vertically thinking about execution order
-  how many clicks does it take to set up (autocompletion and context awareness is important - its competing with typing which is tough)
-  How much empty space is wasted - how efficiently is it using the space - less scrolling and eye travel = better
- How does it scale with a lot of logic - searching and replacing logic/ ability to reuse logic

**Comment by CosmoMyzrailGorynych** [comment]
> Your current approach is very similar to scratch, which I am not a fan of - since its slower to use, but almost the same as coding. It doesnt take enough advantage of the visual side of coding.

The UI is mostly inspired by Scratch, correct. By the way, linear-grammar languages were easier to understand for newcomers than node languages, at least in my observations as a teacher.

About slow use, it is all about UX/UI and what blocks can do. I think ct.js will handle this downsight of other linear grammar languages pretty nicely.

> I would personally prefer if conditions were in their own left side column -similar to construct and develop.

And such things, personally, make me vomit. Especially with gdevelop where code constructs become fuzzy when you refer to entities used in events. Explicity and control make it better, especially if blocks are used as an educational tool for further JS learning.

> Another thing that helps alot is having little thumbnails of objects being generated from their sprites. It makes it much easier to see and find logic associated with enemies/npc/players at a glance.

Good point. I think inputs with such thumbnails will appear during the implementation. I have all the tools to do it thanks to already existing components.

> One killer feature that ct.js can totally hit out of the park compared to the others is the ability to make event nodes with javascript.

It is being solved rn with #215  
Though it is targeted to extensions and ct.IDE mainly. YoYo Game Maker had such a feature for regular users (called Triggers), and they removed it later as no one really used it. I think such a feature would come to the same fate if ct.IDE's and modules' own events are advanced and customizable enough.

**Comment by CosmoMyzrailGorynych** [comment]
NO

**Comment by CosmoMyzrailGorynych** [comment]
Yay
