### ISSUE TITLE
✨ Use Tauri instead of Electron for desktop game builds

### ISSUE THREAD

**Issue by FlipFloop** [ct-js/ct-js-old#379]
**Is your feature request related to a problem?**
No, just huge build sizes.
[Tauri](https://tauri.app/) is a superb solution that has made me move away from Electron entirely.

**Describe the solution you'd like**
We should build for web, and just import the HTML into a Tauri project and build there. It would result in much smaller desktop sizes.

**Describe alternatives you've considered (optional)**

**Additional context**

**Comment by CosmoMyzrailGorynych** [comment]
What about steamworks support?

**Comment by FlipFloop** [comment]
How does it work right now? This should just make a smaller executable.

**Comment by CosmoMyzrailGorynych** [comment]
It doesn't right now, yet in perspective, electron builds could use steamworks integration (aka greenworks), which everyone publishing a ct.js game on steam would want.

**Comment by FlipFloop** [comment]
Uhm, [Greenworks](https://github.com/greenheartgames/greenworks) says to not use them anymore? There are alternatives though. Anyway for Rust/Tauri there isn't a [plugin](https://tauri.app/v1/guides/features/plugin/) I've seen yet but maybe one can be written. 
I'll look into this. I just want build sizes to shrink for desktop ATM.

**Comment by FlipFloop** [comment]
@CosmoMyzrailGorynych @markmehere
I've converted a web build of the Dungeon Crawler Example to a Tauri MacOS app in 5 minutes. And built the same Example through **ct** and nw.js (the normal export option).
Here is the difference in output size. Only issue I ran into was sound didn't work, but I'm sure a quick config and digging would fix that.
![Screen Shot 2022-10-03 at 00 03 53](https://user-images.githubusercontent.com/19635051/193499973-8be58513-e5c9-45fe-b191-6c6b59386e8c.png)

**Comment by markmehere** [comment]
@FlipFloop Dungeon Crawler uses ogg. Apple/Safari (and their WebKit variants) don't support ogg. A solution is to give the user multiple export options. I was going to actually roll my own app wrappers - but I actually think your idea @FlipFloop done right could be superior.

One thing @CosmoMyzrailGorynych is running up against is Gitlab build limit constraints so a solution that reintroduces ffmpeg to convert the oggs to mp3s might not be possible.

As you get further into Safari, you'll notice there's a lot of differences between Chrome and Safari. At the same time 200 MB is massive demand on user for a small game. It's a consistency vs file size decision for game developers. I'd pick file size and debug on every platform but others want things to just work.

(typed on Chrome because the inability to copy and paste images in Messenger and take calls on it drives me crazy)

**Comment by CosmoMyzrailGorynych** [comment]
A friendly reminder that Tauri and everything "make crossplatform apps with a small lib!" require installing WebView2 on Windows 10, which is, with electron, essencially swapping one huge dependency with another and making users install it manually.
Also everything before windows 10 will use internet explorer.

Aaaand all in all, I'm against runtime zoo. There will be hidden issues no one will want to deal with. Tauri might be an alternative to electron builds, but not the default one.

And while I remember it, another hidden cost of this feature: extending ct.desktop and ct.fs catmods to support Tauri.

**Comment by markmehere** [comment]
Just quietly 🤐, I really love WebView2! It is a shared Microsoft-signed huge dependency and I suspect in time will become a default framework (Windows 12 🤞).

Good pick up on the `ct.desktop` and `ct.fs` requirements. Sounds like this [isn't a show-stopper](https://tauri.app/v1/api/js/fs/) for Tauri and probably would be for rolling my own solution.

One thing to note because Ct.js is exporting using Electron not Nw.js - we should be able to get ARM support with quick update of [electron-packager](https://github.com/electron/electron-packager).

Overall I'm still in favour. Though Cosmo rightly has a lot more sway on the final decision. I don't have a solution for the ogg to mp3 problem. Probably we hard-code an ffmpeg download url in ct.js from [ffmpeg.org](https://ffmpeg.org/). But at the core of my reasoning, I just don't think people will rightly think any of my games (or others) justify a 200MB+ download.

**Comment by CosmoMyzrailGorynych** [comment]
> Probably we hard-code an ffmpeg download url in ct.js from [ffmpeg.org](https://ffmpeg.org/).

https://www.npmjs.com/package/ffmpeg-static can be used, too

**Comment by FlipFloop** [comment]
So @markmehere you're in favor of Tauri? I was reading up on the [Tauri docs](https://tauri.app/v1/guides/building/cross-platform) and trying to scheme. I don't get this whole `ogg` stuff though. Also,  
> Good pick up on the `ct.desktop` and `ct.fs` requirements. Sounds like this [isn't a show-stopper](https://tauri.app/v1/api/js/fs/) for Tauri and probably would be for rolling my own solution.

Tauri comes with many, many plugins like this. I think honestly we can get away with building for the web, then moving the generated files in a default Tauri project, changing some parameters in the config files, and then building from there...

**Comment by markmehere** [comment]
@FlipFloop I've been thinking it over and yes I am in favour of Tauri! Regarding ogg...

https://caniuse.com/ogg-vorbis

The thing is the lack of Ogg Vorbis extends to the game when visited by Safari on the web or iOS. So maybe we should solve it once and for all. My instinct is to do the Ogg-to-MP3 conversions for the user, but there is a compelling case to just warn the user (e.g. you're using ogg - you won't get any sound for those music/sound files in Safari).

**Comment by CosmoMyzrailGorynych** [comment]
> My instinct is to do the Ogg-to-MP3 conversions for the user

If you will make it, I'll gladly merge it. It's a feature I always wanted in ct.js IDE.

**Comment by FlipFloop** [comment]
So what are the steps to be taken? Do we first enable OGG, then I can make this branch? Or all at once?

**Comment by markmehere** [comment]
> Do we first enable OGG, then I can make this branch?

No. I'm of the view go simple. Warn users when they add or import an ogg into Ct.js that Apple Safari/iOS will not be supported. Running the following code on this [website](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_audio) in Safari 15.6.1 on macOS 12.5.1 fails (no audio), but it succeeds on Chrome.

```
<!DOCTYPE html>
<html>
<body>
<audio controls>
  <source src="horse.ogg" type="audio/ogg">
</audio>
</body>
</html>
```

The "partial" from [caniuse.com](https://caniuse.com/ogg-vorbis) is uselessly technical for an everyday reader and insufficiently detailed for a technical reader. We keep it simple something like "⚠️ ogg sound files will not play on Safari/iOS". I would just keep that warning present all the time, I wouldn't even wait for them to import something.

>  Or all at once?

No. I would do that warning as its own short pull request before any other. Users probably need to be advised regardless of what we implement with desktop exports. Otherwise they're going to be mystified why they aren't getting in sound on their iPhone (like I was first time).

**Comment by markmehere** [comment]
> My instinct is to do the Ogg-to-MP3 conversions for the user

> No. I'm of the view go simple. Warn users when they add or import an ogg...

Oh man I completely changed my mind on this one. 😁 But warning them is the preferred solution I'm locking in.
