### ISSUE TITLE
Trojan in WebInstaller

### ISSUE THREAD

**Issue by biratko** [ct-js/ct-js-old#499]
I followed the link on the main page of the GitHub project (https://ctjs.rocks/) and downloaded the web installer. During installation, the anti-virus program began to swear:
Type: Trojan
Name: PDM:Trojan.Win32.Generic
Object: C:\Users\...\ctjsWebInstaller.exe

I took the zip archive from the release page, no viruses.

Maybe you need to remove the link to this site?

**Comment by CosmoMyzrailGorynych** [comment]
A classical false report from an antivirus.
@biratko what antivirus are you using?

**Comment by biratko** [comment]
Kaspersky

**Comment by CosmoMyzrailGorynych** [comment]
If someone has false positives, please report them to your antivirus provider. (can be googled with "report false positive in XYZ antivirus".)
This has nothing to do with web installer's code but is about antiviruses choosing to blanket-ban all new apps with network and/or file activity instead of doing the real app analysis.
