### ISSUE TITLE
Consider using Crowdin

### ISSUE THREAD

**Issue by mnchrmxd** [ct-js/ct-js-old#548]
# What?
Crowdin is a freemium i18n management platform.

# Why?
I expect it will be easier for translators as you can add screenshots and context for each string and it integrates with GitHub.

# Note!
The free plan at Crowdin is limited, however, the service is unlimited for open source projects with some requirements that I guess ct.js meets.
Create an account and a project, then [submit a request to join the program](https://crowdin.com/page/open-source-project-setup-request).

**Comment by CosmoMyzrailGorynych** [comment]
Do you know anything about supported formats and how it expects translation files to be organized?

**Comment by mnchrmxd** [comment]
Hi, @CosmoMyzrailGorynych
Crowdin supports many formats such as JavaScript, JSON, Markdown and even images (by downloading, editing offline and then uploading).
As for the organisation part, I'm not sure what the question is but it translates each file individually or all strings together depending on the translator's preference, sources can be organised in folders, and if you used GitHub, it will import translation files in folders as is in the GitHub repository.
For export name: 
![Screenshot_٢٠٢٤-١١-٠٩-١١-٤٦-٢٤-٢٧_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/ad1620a8-caa7-4ec8-8945-0dc7dc9fe8db)

**Comment by CosmoMyzrailGorynych** [comment]
I see. Yes, this is the information I need, I suppose.
Will need to toy around it someday.
It's important for me to preserve the current file format and structure as one should not rely on a 3rdparty freemium service that may change their mind on a whim.

**Comment by ReptiIe** [comment]
Depending of the results (how it will look and work at the end) - I am against this idea (to use crowdin or any other 3rd apps/sites for translations). And I have a full list why not use it.
It is extremely uncomfortable.
 
Good things:
- Yes, it is in 1 place, everything, each translation, 
- it has connections, there is also some "dictionary", or some AI that could "suggest" some translations. 
- This way surly everyone can contribute and help out with the translations

Issues that I personally run into:
- You see strings, but hell you have no idea where they are, to what they are connected, you have to figure it out by yourself 
- When something will get update, I simply have no idea as a translator when my translated words are merged 
- Everyone can contribute; that means also bots and random users that have bloody no idea what is going on, in results YES you will get a faster translation of the app, but in reality it will be a mess since 1 term can be translated in many ways, and it will be translated like that by many users. 

Examples that I run into:
* SPRITE; graphics. Everyone knows what is a sprite, image or something. What is the translation?? In polish they translated this into "GHOST" (another great example, once we have SPRITE as SPRITE, one time we have SPRITE as graphics and there is another time SPRITE as GHOST... see the issue?)
* Bugs, Debugging, Debugger; another term that is know. How it was translated - literary someone translate this into BUGS! (Bugs are like, let we call it "errors" right? Not BUGS as WORMS!)

We can solve those issues by selecting some person who will be the head translator or something and will accept translated stuff, which one are ok, which one are not, but again this option is "speed" over "quality" I would say.

Another thing: 
@CosmoMyzrailGorynych you will have to loose time to learn some new system, manage it, for... seriously I do not know what reason (why is that - a little bit below: in translating ctjs is easy...). You could use this time more efficient for rewriting ctjs into neutralino, and perhaps prepare the app to be compatible with ARM (Raspberries Pi etc).

As for the Crowdin, "is it better"; not really. It does have some good points, yes,
but as I see CTJS for now, there are ABSOLUTLEY NO ISSUES! With translations.

Translating CTJS is easy.  
Download the JSON file, open in whatever you are using text editor, and go on with translation.
Need help? Ask google, look in some dictionaries etc.
You want to know where is the line, or maybe you would like to see progress of your translation?
Hey, just save the file, place it in app, use it, and you can see everything. On the go!

No need to wait up for anyone to approve, accept, merge, etc.
Everything goes smoothly when it comes to translation.

Another thing... You want to translate/help with the translate,
Translate the file, send it over via Discord, or here on Github.
No need for extra another accounts, comments, rates, systems.

**Comment by CosmoMyzrailGorynych** [comment]
For the record, I created https://comigo.itch.io/jsonbabel exactly for translating JSON files in ct.js and my other projects, and it supports Comments.json file that tells which field is which, _if_ it is documented. Also there is a special "Debug" language in ct.js that displays the translation keys as values.

**Comment by ReptiIe** [comment]
I just wanted to be clear from above when I mention "I do not know what is what"
Like I said: right now all you need is whatever text editor you are working with, and you are good to go.

Since I can upload my translation (in my local PC, in my local app)
I can see it on the go, where is what.

Let me give a simple example again... So it will not be complicated, again I will use "SPRITE"

Let we say in translation file we have, line 200: "SPRITE" (or different word)
I do not know what that is as a translator... or what this thing DOES, or where it is displayed...
I can MARK in my local translation like: "!!! SPRITE !!! "
Or I can translate it "!!! GHOST !!!"

When I will check CTJS, and check all the words, all the buttons, all options, commands what it functions and options are doing what, surly I will find this "!!! GHOST !!!" and I will be able to translate that properly.

Now the worst case scenario is when we are translating something,
and one person will translate something (ex. SPRITE) as SRPITE,
in some different line a different person will translate SPRITE as GRAPHIC
and somewhere else we will have SPRITE as GHOST.

Simply said: 
1 translator - 1 file; no issues
many translators - 1 file; big issues, and a lot of problem will be generated.

**Comment by CosmoMyzrailGorynych** [comment]
> Now the worst case scenario is when we are translating something,
> and one person will translate something (ex. SPRITE) as SRPITE,
> in some different line a different person will translate SPRITE as GRAPHIC
> and somewhere else we will have SPRITE as GHOST.

This is usually solved by publishing a dictionary with used terminology for each language.

**Comment by mnchrmxd** [comment]
Hi, @ReptiIe

> You see strings, but hell you have no idea where they are, to what they are connected, you have to figure it out by yourself

This may be solved by adding context and a screenshot with the string.

> Everyone can contribute; that means also bots and random users that have bloody no idea what is going on, in results YES you will get a faster translation of the app, but in reality it will be a mess since 1 term can be translated in many ways, and it will be translated like that by many users.

You are right on this point, I translate and proofread Arabic translations for GDevelop, I struggle with people who just pick and choose machine translation suggestions and standardize terminology. We may make the project private or enterprise but I don't know if it is free for FOSS projects.

> Another thing... You want to translate/help with the translate,
Translate the file, send it over via Discord, or here on Github.
No need for extra another accounts, comments, rates, systems.

Good point. BTW, Crowdin makes translation easy as I get notified when new strings are available for translation.

**Comment by ReptiIe** [comment]
Yes I know that you are in the GDevelop team, so you should understand my point :)
