### ISSUE TITLE
Templates -> Button - not working with circle or polygon coliders.

### ISSUE THREAD

**Issue by returnworld** [ct-js/ct-js-old#552]
**Describe the bug**
Templates -> Button - not working with circle or polygon coliders, work only with rectangle.

**To Reproduce**
1) create Templates -> Button with circle colider texture.
2) add to UI room.
3) run

**Expected behavior**
Uncaught Error: [u.reshapeNinePatch] Cannot reshape a circular collision mask for undefined. Please use a different collision type for its texture.
Error: [u.reshapeNinePatch] Cannot reshape a circular collision mask for undefined. Please use a different collision type for its texture.

**System information report**
Ct.js v5.2.1 😽 (packaged)

NW.JS v0.72.0
Chromium v109.0.5414.87
Node.js v19.3.0
Pixi.js v7.3.2

WebGL available
WebGL vendor Google Inc. (NVIDIA)
WebGL renderer ANGLE (NVIDIA, NVIDIA GeForce GTX 1650 SUPER Direct3D11 vs_5_0 ps_5_0, D3D11)
OS win32 x64 // Windows_NT 10.0.19045

**Comment by CosmoMyzrailGorynych** [comment]
Polygons do work, enable collision visualization in Project tab -> Place -> Debug mode if you have problems. If it is not, post screenshots and proper reproduction steps.
And with circles, I think the error message is more than explanatory.

**Comment by returnworld** [comment]
Сorrection, yes, the polygon is work, but broken center image.
I prepared a project with the problem, you can change the template type to sprite and back to button, for understand the problem.
There are 2 templates in it, one for a button with a circle and one for a button with a polygon.
[error.zip](https://github.com/user-attachments/files/17710094/error.zip)

**Comment by returnworld** [comment]
![image](https://github.com/user-attachments/assets/af394374-6264-462a-8f5a-9b530f083720)

**Comment by returnworld** [comment]
![image](https://github.com/user-attachments/assets/77665bcb-1037-4713-955a-b383c816d460)
if circle template its a button, i have this error, dont know may be I didn't configure something in ct.js?

**Comment by returnworld** [comment]
if we added matter.js physics to this polygon-button we get 
![image](https://github.com/user-attachments/assets/2d9ffb3a-fa7f-44d1-b870-593517158282)

**Comment by CosmoMyzrailGorynych** [comment]
You are bloating the issue. For the `matter` module, maintain a separate issue. Personally I don't think the matter catmod should even work with Button base classes. Buttons are base classes for elements that need to stretch nicely (9-patch) and have a text on top of it. For simple clickable sprites w/o text, use Animated Sprite base class.

With circles, the error clearly states that circular collision masks are not supported for Buttons. The only thing that can be is that the IDE can warn about an incorrect collider shape for a used template and hint users that they probably need an Animated Sprite instead of a button.
